name: TruffleHog Secret Scan

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  trufflehog:
    name: Secret Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for better detection
      
      - name: Debug Git Info
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Base SHA: ${{ github.event.pull_request.base.sha || github.event.before }}"
          echo "Head SHA: ${{ github.event.pull_request.head.sha || github.event.after }}"
          echo "Default Branch: ${{ github.event.repository.default_branch }}"
          git log --oneline -10
          
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          base: ${{ github.event.pull_request.base.sha || github.event.before }}
          head: ${{ github.event.pull_request.head.sha || github.event.after }}
          # Only fail on verified secrets to reduce false positives
          # This scans only the commits in the PR or push, not the entire history
          extra_args: --only-verified --fail --exclude-paths .trufflehog-ignore